chore(front): kepler panel style commit
datatlas-erasme/datatlas pull request #122
Opened 2023-03-31 10:02 UTC by OlivPi

2023-04-20 13:32 UTC, Pipazoul commented
@OlivPi could you merge/rebase the `dev` branch on your `style-kepler-customizations`  befor making a pull request, some files are overwritten by your branch ex: '.env.example`

2023-04-20 14:55 UTC, lutangar requested changes

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/AddDataButtonFactory.tsx
> +export function AddDataButtonFactory() {
Missing blank line between imports and first line of code.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/KeplerGlFactory.tsx
>  // Maybe we should think about exporting this or creating a variable
You should delete this comment and code.
But you could add, for example, a comment on why this global style was deleted and where to find the new one.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerConfiguratorFactory.tsx
> -
You should keep this blank line.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerConfiguratorFactory.tsx
> +    console.log('ÇA JAZZ : ' + layer);
It does Jazz :saxophone: but shouldn't appears here.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerManagerFactory.tsx
> +// const StyledFormSidePanel = styled.form`
Should be removed.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerManagerFactory.tsx
> +            Un trop grand nombre de jeux de données peut altérer le projet
Should be translated.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerManagerFactory.tsx
> +            Un trop grand nombre de jeux de données peut altérer le projet
Should be translated.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerManagerFactory.tsx
> +            <FormattedMessage id={'layerManager.fileformat'} />
Use `camelCase` for the dictionnary keys :
```suggestion
            <FormattedMessage id={'layerManager.fileFormat'} />
```

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerManagerFactory.tsx
> +              id={'layerManager.contactus'}
```suggestion
              id={'layerManager.contactUs'}
```

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerManagerFactory.tsx
> +              id={'layerManager.contactus'}
```suggestion
              id={'layerManager.contactUs'}
```

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/LayerManagerFactory.tsx
> +              id={'layerManager.contactus'}
```suggestion
              id={'layerManager.contactUs'}
```

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/PanelHeaderFactory.tsx
> +//deps : variable statique, stocker tout les arguments de la fonction =>  Injection de dépendence
You can keep this but try to translate it.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/PanelTitleFactory.tsx
> +//deps : variable statique, stocker tout les arguments de la fonction =>  Injection de dépendence
Duplicated comment.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/PanelToggleFactory.tsx
> +const propTypes = {
`PropTypes` was the way to "type" props when Typescript wasn't a thing.
 You may use this definition to write a new interface for the props of the component but you must then remove it.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/PanelToggleFactory.tsx
> +  const PanelToggle = ({ activePanel, panels, togglePanel }) => {
@todo type the props with new interface you're going to create.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/PanelToggleFactory.tsx
> +  PanelToggle.propTypes = propTypes;
You may remove this once the props interface is created.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/configurator/AggregationTypeSelector.tsx
> +      <h2>CONTENT</h2>
Is this a test ? If not you should translate it.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/configurator/ArcLayerColorSelector.tsx
> +    <h2>ColorSelector</h2>
Is this a test ? If not you should translate it.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/configurator/LayerColorRangeSelector.tsx
> +    <h2>COUCOU</h2>
Probably a test.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/index.ts
> +import { replacePanelTitle } from './factories/PanelTitleFactory';
You should import this as the other replace functions.
To do so, you must re-export each function in the `factories/index.ts` file.
It's known as a barrel file : https://basarat.gitbook.io/typescript/main-1/barrel

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/components/keplerGl/side-panel/layer/LayerPanel.tsx
> +      {/*A quelle parti appartien ce header ?*/}
I don't know but keep it just in case.

2023-04-20 14:55 UTC, lutangar commented on apps/frontend/src/i18n/messages/en.ts
> +  'layerManager.fileformat':
You should use `camelCase` for the key and change it where it appears.
Same goes for the keys below ....

2023-04-24 15:54 UTC, lutangar requested changes

2023-04-24 15:54 UTC, lutangar commented on apps/frontend/src/components/buttons/Button.tsx
> +export const Button = ({ children, Icon, onClick, type }: ButtonInterface) => {
The interface defines the props of the button components and not the button itself and therefore should rather be named `ButtonPropsInterface`.

2023-04-24 15:54 UTC, lutangar commented on apps/frontend/src/components/buttons/Button.tsx
> +  className?: string;
It seems these props aren't used... or maybe shall the be injected as the rest props in the child component ?
> see for example https://stackoverflow.com/questions/43484302/what-does-rest-mean-in-react-jsx

2023-04-24 15:54 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/PanelHeaderFactory.tsx
> -
This line should probably be kept.

2023-04-24 15:54 UTC, lutangar commented on apps/frontend/src/components/keplerGl/factories/PanelToggleFactory.tsx
> +  const PanelToggle = ({ activePanel, panels, togglePanel }) => {
Ping.

2023-04-26 10:39 UTC, merged