Project datasets notion
datatlas-erasme/datatlas pull request #215
Opened 2023-06-13 10:10 UTC by racine-p-a

Notion helper receiving notion json data and sending back corresponding geojson data.

2023-06-13 14:09 UTC, lutangar requested changes

2023-06-13 14:09 UTC, lutangar commented on libs/notion/src/lib/notion.spec.ts
> +// Launch it using : jest path/to/project/datatlas/libs/notion/src/lib/notion.spec.ts while being in datatlas folder.
It should be runable via the builtin command `nx test notion`.

2023-06-13 14:09 UTC, lutangar commented on libs/notion/src/lib/notion.spec.ts
> +      const jsonString = fs.readFileSync('./libs/notion/src/lib/data_test.json', 'utf-8');
You should rely on import instead of a `fs` function, path resolution might be hazardous otherwise :
```
import jsonData from './notion/src/lib/data_test.json';
```

> `json` files can be imported as any `js` file.

2023-06-13 14:09 UTC, lutangar commented on libs/notion/src/lib/notion.spec.ts
> +      const jsonString = fs.readFileSync('./libs/notion/src/lib/data_test.json', 'utf-8');
`JSON.parse` won't be necessary if imported as a module.

2023-06-13 14:09 UTC, lutangar commented on libs/notion/src/lib/notion.ts
> +  return '';
Could be a typical `switch` `case` usecase:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch

2023-06-13 14:09 UTC, lutangar commented on libs/notion/src/lib/notion.ts
> +    return '';
In most unexpected use cases you might `throw` an error instead of returning an empty string.

2023-06-13 14:09 UTC, lutangar commented on libs/notion/src/lib/notion.ts
> +    return '';
Or not if this is expected behavior !

2023-06-13 14:15 UTC, lutangar commented on libs/notion/src/lib/notion.spec.ts
> +      const jsonString = fs.readFileSync('./libs/notion/src/lib/data_test.json', 'utf-8');
https://stackoverflow.com/questions/49996456/importing-json-file-in-typescript

2023-06-13 14:36 UTC, racine-p-a commented on libs/notion/src/lib/notion.spec.ts
> +      const jsonString = fs.readFileSync('./libs/notion/src/lib/data_test.json', 'utf-8');
As seen and tried with you, can't import json directly :/

2023-06-14 11:29 UTC, lutangar approved these changes

2023-06-14 11:29 UTC, lutangar commented on libs/notion/src/lib/notion.ts
> +  switch (jsonContent.type) {
:heart_eyes:

2023-06-14 11:30 UTC, merged