chore(front): edit readme with figma sketch link
datatlas-erasme/datatlas pull request #51
Opened 2023-01-18 14:18 UTC by OlivPi

2023-01-19 09:19 UTC, lutangar requested changes

2023-01-19 09:19 UTC, lutangar commented on README.md
> +**Figma** sketch : `https://www.figma.com/proto/lVX7Lycox3AGixBhhbhQsQ/DatAtlas?page-id=592%3A7135&node-id=600%3A8166&viewport=727%2C1558%2C0.5&scaling=min-zoom&starting-point-node-id=600%3A8044`.
Could you please remove the extra parameters ?
So we may land on the main page instead :
https://www.figma.com/file/lVX7Lycox3AGixBhhbhQsQ/DatAtlas

2023-01-19 09:19 UTC, lutangar commented on README.md
> +#### Style
```suggestion
## Design
```

2023-01-19 09:19 UTC, lutangar commented on README.md
> +#### Style
Would me more appropriate as a level 2 title later in the document.
We could also mentions the company behind the design.

2023-01-19 13:32 UTC, Pipazoul approved these changes

2023-01-23 10:01 UTC, lutangar commented on README.md
> +#### Style
> Resolved via dffa02fd1592b5c6aab448313bf01d2ce68c2486

2023-01-23 10:01 UTC, lutangar approved these changes

2023-01-23 20:49 UTC, merged