Layout pages
datatlas-erasme/datatlas pull request #69
Opened 2023-02-10 16:36 UTC by OlivPi

2023-02-21 16:02 UTC, lutangar requested changes

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/components/buttons/Button.tsx
> +const KeplerButtonStyle = styled(KeplerButton)`
I think I know what you mean but a more suitable name would be `StyledKeplerButton`.

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/components/buttons/GithubLink.tsx
> +  console.log(bgColor);
:left_speech_bubble:

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/components/card/CardDetails.tsx
> +        <FormattedMessage defaultMessage={'Modifié il y a'} /> {days === 0 ? '' : days + 'j'}{' '}
If we need to translate this to other languages this will be an issue. 
Luxon tackle this feature natively and deal with locales as well :
https://moment.github.io/luxon/api-docs/index.html#datetimetorelative

Anyway, I think I saw this component somewhere else in the code, you could create a dedicated component with this fragment, the only thing this component would need is a `date` props where you would feed the `createdAt` value.

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/components/card/ProjectCard.tsx
> +  console.log(props);
:left_speech_bubble:

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/components/card/ProjectCard.tsx
> +  console.log(props);
:left_speech_bubble:

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/pages/LoginPage.tsx
> +  // useEffect(() => {
:left_speech_bubble:

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/pages/layouts/Layout.tsx
> +  //justify-content: flex-start;
:left_speech_bubble:

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/components/footer/footer.tsx
>  import React from 'react';
`footer.tsx` -> `Footer.tsx`

2023-02-21 16:02 UTC, lutangar commented on apps/frontend/src/utils/rgb2hex.ts
> +export const rgb2hex = (rgb) =>
You should be able to reuse the kepler function instead :
rgbToHex
- import it from `dist/utils/color-utils.js`
- if required add custom typedef in `apps/shared/models/types/kepler.gl/index.d.ts`

2023-02-23 13:44 UTC, OlivPi commented on apps/frontend/src/components/card/CardDetails.tsx
> +        <FormattedMessage defaultMessage={'Modifié il y a'} /> {days === 0 ? '' : days + 'j'}{' '}
I refactored my code to use Luxon and a Hook is called `UseTimeElapsed`

2023-02-23 13:55 UTC, lutangar commented
@OlivPi you marked some of the conversations as resolved but I am not seeing any updates. Did you push the updates already ?

2023-02-23 14:46 UTC, OlivPi commented
Indeed, I had only 'commit' the push had not gone @lutangar .

So, the command line `nx run frontend:lint` lets errors pass while the `nx run frontend:build` is more strict. And i have some failed when un pushed.

2023-02-23 15:14 UTC, lutangar requested changes

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/buttons/Button.tsx
> +    <StyleKeplerButton onClick={onClick} type={type}>
I'm gonna mark the missing changes with :eyes:

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/card/CardDetails.tsx
> +import UseTimeElapsed from '../../hooks/useTimeElapsed';
```suggestion
import useTimeElapsed from '../../hooks/useTimeElapsed';
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/card/CardDetails.tsx
> +  const timeElapseStatus = UseTimeElapsed(createdAt);
```suggestion
  const timeElapsed = useTimeElapsed(createdAt);
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/card/CardDetails.tsx
> +      {timeElapseStatus}
```suggestion
      {timeElapsed}
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/card/MapPreview.tsx
> +  disable: boolean;
"Disable" is a verb but it's not an action, so you probably meant "disabled".
But moreover what's "disabled" here ? If the copy is "disabled" then you could name it `copyDisabled`.

...no I think I remember we mentioned "feature flag", in such context it might make ever more sense to name this props `copyEnabled` instead (but the condition must be changed accordingly).

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/card/ProjectCard.tsx
> +      <MapPreview draft={props.draft} handleRemove={handleRemove} handleCopy={handleCopy} disable={props.disable} />
Need to be updated here too.

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/card/MapPreview.tsx
> +const MapPreview = ({ draft, handleRemove, handleCopy, disable }: MapPreviewInterface) => {
You should set a default, for boolean it's easy :
```suggestion
const MapPreview = ({ draft, handleRemove, handleCopy, copyEnabled = false }: MapPreviewInterface) => {
```

> https://betterprogramming.pub/5-recipes-for-setting-default-props-in-react-typescript-b52d8b6a842c

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/forms/LoginForm.tsx
> +const LoginFormStyle = styled.form`
```suggestion
const StyledLoginForm = styled.form`
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/forms/LoginForm.tsx
> +    <LoginFormStyle onSubmit={handleSubmit(login)}>
```suggestion
    <StyledLoginForm onSubmit={handleSubmit(login)}>
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/forms/LoginForm.tsx
> +const InputLoginStyle = styled(Input)`
```suggestion
const StyledLoginInput = styled(Input)`
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/forms/LoginForm.tsx
> +      <InputLoginStyle id="login" defaultValue="" {...register('login', { required: true })} />
```suggestion
      <StyledLoginInput id="login" defaultValue="" {...register('login', { required: true })} />
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/components/forms/LoginForm.tsx
> +      <InputLoginStyle id="password" type="password" defaultValue="" {...register('password', { required: true })} />
```suggestion
      <StyledLoginInput id="password" type="password" defaultValue="" {...register('password', { required: true })} />
```

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/style/theme.ts
> +export const LabelStyle = styled.label`
```suggestion
export const StyledLabel = styled.label`
```
Don't forgot to update usages as well.

2023-02-23 15:14 UTC, lutangar commented on apps/shared/models/Project.ts
> +  disable: boolean;
What this property is supposed to do ?

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/hooks/useTimeElapsed.tsx
> +const UseTimeElapsed = (createdAt) => {
Please take a closer look at the documentation of `toRelativeCalendar` in `luxon` it does exactly what we need :
https://moment.github.io/luxon/api-docs/index.html

And do use the locale as in :
```js
DateTime.now().plus({ days: 1 }).toRelativeCalendar({ locale: "fr" })
//=> "demain"
```

But instead of `'fr'` we should be able to get the locale someway via `react-intl`.

2023-02-23 15:14 UTC, lutangar commented on apps/frontend/src/hooks/useTimeElapsed.tsx
> +const UseTimeElapsed = (createdAt) => {
```suggestion
const useTimeElapsed = (createdAt) => {
```

A hook name start with a lower case.

2023-02-23 15:21 UTC, OlivPi commented on apps/frontend/src/hooks/useTimeElapsed.tsx
> +const UseTimeElapsed = (createdAt) => {
Yes

2023-02-23 15:41 UTC, OlivPi commented on apps/frontend/src/style/theme.ts
> +export const LabelStyle = styled.label`
Old usage that has been forgotten

2023-02-23 16:11 UTC, OlivPi commented on apps/frontend/src/components/card/MapPreview.tsx
> +const MapPreview = ({ draft, handleRemove, handleCopy, disable }: MapPreviewInterface) => {
I understand better how to properly implement this now. Thanks

2023-02-24 08:14 UTC, OlivPi commented on apps/frontend/src/hooks/useTimeElapsed.tsx
> +const UseTimeElapsed = (createdAt) => {
I change my method to use `toRelativeCalendar`. But, i have a little with the unit. I would like to be more specific as my actual result. `ToRelativeCalendar` just accept one `string` value, and i'll like to pass an array like `const unit = ['days', 'hours', 'minutes'];`. But i get an error.

2023-02-27 18:27 UTC, lutangar commented on apps/frontend/src/components/buttons/Button.tsx
> +const StyleStyleKeplerButton = styled(StyleKeplerButton)`
Hum something went wrong since last review... :thinking:

2023-02-27 18:27 UTC, lutangar commented on apps/frontend/src/components/card/MapPreview.tsx
> +        {copyEnabled ? '' : <IconButton Icon={<Copy />} onClick={handleCopy} />}
JSX trixxx :
```suggestion
        {copyEnabled && <IconButton Icon={<Copy />} onClick={handleCopy} />}
```

2023-02-27 18:27 UTC, lutangar commented on apps/frontend/src/pages/ComponentsPage.tsx
> +            <Checkbox id="test" label="label" checked copyEnabledd={false} />
```suggestion
            <Checkbox id="test" label="label" checked copyEnabled={false} />
```

2023-02-27 18:27 UTC, lutangar commented on apps/shared/models/Project.ts
> +    this.copyEnabled = project.copyEnabled;
This feature is related to the UI and shouldn't appears in the User model.

2023-02-27 18:27 UTC, lutangar commented on apps/shared/models/mocks/generators.ts
> +  copyEnabled: true,
Remove.

2023-02-27 18:27 UTC, lutangar commented on apps/shared/models/ProjectInterface.ts
> +  copyEnabled: boolean;
Remove.

2023-02-27 18:27 UTC, lutangar commented on apps/shared/models/Project.ts
> +      copyEnabled: true,
Remove.

2023-02-27 18:27 UTC, lutangar commented on apps/shared/models/Project.ts
> +      copyEnabled: true,
Remove.

2023-02-27 18:27 UTC, lutangar commented on apps/shared/models/Project.ts
> +  ): Omit<ProjectInterface, 'owner' | 'id' | 'draft' | 'contributors' | 'copyEnabled'> {
Remove.

2023-02-27 18:27 UTC, lutangar commented on apps/frontend/src/hooks/useTimeElapsed.tsx
> +};
:tada:

2023-02-27 18:27 UTC, lutangar commented on apps/frontend/src/hooks/useTimeElapsed.tsx
> +};
On last thing though... You should use an i18n method for : "Projet modifié"

2023-02-27 18:27 UTC, lutangar commented on apps/frontend/src/components/buttons/GithubLink.tsx
> +      <p>Lien vers le Github du projet :</p>
i18n :fr:

2023-02-27 21:17 UTC, lutangar commented on apps/frontend/src/hooks/useTimeElapsed.tsx
> +};
Didn't notice but, the logic is wrong here :
- now value isn't now but "tomorrow"
- `const timeElapsed = DateTime.fromISO(createdAt);` variable name is wrong

2023-02-28 10:38 UTC, merged