Dev pa user
datatlas-erasme/datatlas pull request #72
Opened 2023-02-20 11:07 UTC by racine-p-a

CRUD user integration. Might (should) be completed  few times later.

2023-02-20 13:10 UTC, lutangar requested changes
Glad this PR land in review !
I let you deals with the details and let's discuss about users and the JWT authentication later tomorrow...

2023-02-20 13:10 UTC, lutangar commented on apps/backend/.env.example
> +POSTGRES_DATABASE=gis
We could suggest a more meaningful database name as a the default, for example:
`datatlas`

2023-02-20 13:10 UTC, lutangar commented on apps/backend/cypress/e2e/user.cy.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
We must keep this safeguard active. There might be a configuration issue somewhere which forbid this import. Let's find out together...

2023-02-20 13:10 UTC, lutangar commented on apps/backend/cypress/e2e/user.cy.ts
> +    // TODO
Shall we be able to list all users ? Probably an admin should be able to this...

2023-02-20 13:10 UTC, lutangar commented on apps/backend/cypress/e2e/user.cy.ts
> +    cy.request({
You could share the request config as you shared the test user.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/cypress/e2e/user.cy.ts
> +      const userToReceive = new UserPublicDTO(id_test_user, test_user.username, test_user.role, test_user.active);
Maybe a constructor which accepts a single user like object as an argument would be more practical.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/cypress/e2e/user.cy.ts
> +      // todo to finish
Let's do it then !

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/app/app.controller.spec.ts
> +/*import { Test, TestingModule } from '@nestjs/testing';
Why is this block of code commented ?

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/app/app.controller.ts
> +    //return this.authService.login(req.user);
Not functional yet ?

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/app/app.controller.ts
> +    Logger.log(req);
If you want to keep this log line in the codebase, you should probably use `Logger.debug` or `Logger.verbose` methods instead. Or else you'd probably want to remove it.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/app/app.module.ts
> +import { JwtService } from '@nestjs/jwt';
There is no rules enforcing it or auto-fixing this at the moment but you may want to keep third party imports at the top.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/auth/auth.service.ts
> +    //const user = await this.userService.findOne(username);
Not functional yet ?

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/auth/auth.service.ts
> +    /*
Any particular issue with the JWT authentication ?

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/auth/constants.ts
> +  secret: 'secretKey', // todo : place env variable here
Yup :+1:

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/config/mikro-orm.ts
> +const postGresHost = process.env.POSTGRES_HOST || 'localhost';
If these variables are only used once you may omit them.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/cypress.config.js
> +    baseUrl: 'http://localhost:3333',
You should use th `PORT` env variable instead.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/auth/jwt.strategy.ts
> +  async validate(payload: any) {
Commented code block.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/project/project.controller.ts
> +  async fetchAll(): Promise<ProjectEntity[]> {
This method might return all projects for an admin but should return only user's project for a standard user.

It might as well be another method sending projects for user X .

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.controller.spec.ts
> +/*
Let's talk  about users and authent' then !

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.controller.ts
> +   * TODO : Guard ?
Yup, an admin can probably do that but a user may only do that on his profile.
Didn't check if it was the case, but password mustn't appears in the request payload.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.controller.ts
> +   * TODO put a guard here but which one ?
Maybe not know but we should have an email verification.
But at least a"well formed email" for now.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.controller.ts
> +    //Logger.log(params);
You probably want to remove these lines;

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.controller.ts
> +  async updateUser(@Param() params, @Body() user: { user_id: number } & UserDto): Promise<void> {
Where does this *underscore* case comes from ? `user_id`
If we want to be consistent with the rest, you probably want to use `camelCase` everywhere.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.controller.ts
> +   * TODO : guard
Only for admin I suppose.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +      if (isItIn) {
You could use a ternary operator.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +      });
You could the following shorthand version :
```suggestion
      return this.userRepository.persistAndFlush(user).then(() => this.getUserIDByUserName(user.username));
```

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +      //Logger.log(util.inspect(data_user, false, null, true));
Leftover debug comment.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +     */
You may have a look at the official documentation on how it's supposed to be done in mikro orm : https://mikro-orm.io/docs/entity-helper
 
I think you did something fancier on the `project` entity `update`. You might as well reuse what you did.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +      // Should we really do nothing ?
Yeah why not, throwing an error or returning nothing if everything went well is ok... as long as the error part is actually happening, if the associated test doesn't then it definitely could.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +        return 0;
This could be misleading since the `userId` is also a number. You might as well return null.

2023-02-20 13:10 UTC, lutangar commented on apps/backend/tsconfig.json
> +  "compilerOptions": {
I think it's already in the base tsconfig, if so, you shouldn't redeclare these options here.

2023-02-20 13:10 UTC, lutangar commented on apps/frontend/public/mockServiceWorker.js
> +    ;(async function () {
I suppose you accidentally run some kind of code style fix on this frontend file. This change should not apear here.

2023-02-20 13:10 UTC, lutangar commented on apps/shared/models/dto/user/user.dto.ts
> +    private user_name: string,
You should use `camelCase` here as well.

2023-02-20 13:10 UTC, lutangar commented on apps/shared/models/dto/user/userPublic.dto.ts
> +  constructor(user_id: number, user_name: string, user_role: string, user_is_active: boolean) {
`camelCase`  for consistency sake.

2023-02-23 13:49 UTC, racine-p-a commented on apps/backend/cypress/e2e/user.cy.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
I have no clue how to import it in usual way :/

2023-02-23 13:50 UTC, racine-p-a commented on apps/backend/.env.example
> +POSTGRES_DATABASE=gis
Done by @Pipazoul on another PR, it will be merged

2023-02-23 13:51 UTC, racine-p-a commented on apps/backend/cypress/e2e/user.cy.ts
> +    // TODO
No guards at all for now. It's done as a PoC for now.

2023-02-23 13:52 UTC, racine-p-a commented on apps/backend/cypress/e2e/user.cy.ts
> +    cy.request({
What do you mean ? The request body ? If so, it's the object at the beginning of the test file.

2023-02-24 10:01 UTC, racine-p-a commented on apps/backend/cypress/e2e/user.cy.ts
> +      const userToReceive = new UserPublicDTO(id_test_user, test_user.username, test_user.role, test_user.active);
Done.

2023-02-24 10:02 UTC, racine-p-a commented on apps/backend/cypress/e2e/user.cy.ts
> +      // todo to finish
Deleted.

2023-02-24 10:04 UTC, racine-p-a commented on apps/backend/src/app/app.controller.spec.ts
> +/*import { Test, TestingModule } from '@nestjs/testing';
Became (temporarily) useless.

2023-02-24 10:05 UTC, racine-p-a commented on apps/backend/src/app/app.controller.ts
> +    //return this.authService.login(req.user);
Todo, I shouldn't have push it :/

2023-02-24 10:07 UTC, racine-p-a commented on apps/backend/src/app/app.controller.ts
> +    Logger.log(req);
Removed.

2023-02-24 10:08 UTC, racine-p-a commented on apps/backend/src/app/app.module.ts
> +import { JwtService } from '@nestjs/jwt';
Done.

2023-02-24 10:09 UTC, racine-p-a commented on apps/backend/src/auth/auth.service.ts
> +    //const user = await this.userService.findOne(username);
TODO. I shouldn't have pushed this file.

2023-02-24 10:11 UTC, racine-p-a commented on apps/backend/src/auth/auth.service.ts
> +    /*
Yep. Desactivated.

2023-02-24 10:12 UTC, racine-p-a commented on apps/backend/src/auth/constants.ts
> +  secret: 'secretKey', // todo : place env variable here
Waiting for our next meeting. ;)

2023-02-24 10:22 UTC, racine-p-a commented on apps/backend/cypress.config.js
> +    baseUrl: 'http://localhost:3333',
Done

2023-02-24 10:22 UTC, racine-p-a commented on apps/backend/src/auth/jwt.strategy.ts
> +  async validate(payload: any) {
Removed.

2023-02-24 10:25 UTC, racine-p-a commented on apps/backend/src/project/project.controller.ts
> +  async fetchAll(): Promise<ProjectEntity[]> {
Of course. We'll discuss that later.

2023-02-24 12:56 UTC, racine-p-a commented on apps/backend/src/user/user.service.ts
> +        return 0;
I prefer to get same type as return. `0` can not be a `userId` (which is always >0 ) Hence the 0 as a return type.

2023-02-24 13:01 UTC, racine-p-a commented
Outdated. I close this one but I'll make a new one with all merged code (mine + @Pipazoul 's )

2023-02-24 13:01 UTC, closed without merging