Merging all user + project  content
datatlas-erasme/datatlas pull request #79
Opened 2023-02-24 13:04 UTC by racine-p-a

Previous one became outdated. I corrected everything accordingly with @lutangar feedback. In addition, I added projects stuff from @Pipazoul

2023-02-24 15:11 UTC, racine-p-a commented
@OlivPi Need help from you : incoherence in the shared code makes the buil failed.

2023-02-27 08:27 UTC, OlivPi commented on apps/backend/src/user/user.interface.ts
> +  role: string;
I think if you have firstname, we need lastname too. And there is no the email.

2023-02-27 18:18 UTC, lutangar requested changes

2023-02-27 18:18 UTC, lutangar commented on apps/backend/cypress.config.js
> +    baseUrl: 'http://localhost:3333',
You should use `process.env.PORT` instead of a hardcoded value.

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/app/app.controller.spec.ts
> -import { Test, TestingModule } from '@nestjs/testing';
If the controller in `app.controller.ts` is still relevant so the spec file is.

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/config/mikro-orm.ts
> +  debug: true,
Debug option could be dependent of  `process.env.NODE_ENV` variable :
```suggestion
  debug: process.env.NODE_ENV !== 'production',
```

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +      data_user.username = user.username;
Case should be consistent with the rest of the project.
If you need to update many properties, please do create a dedicated method in the `UserDto` class for example:
```js
user.fromUserDto(userDto);
```

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +   * Deletes user. Returns void.
This block comment is useless (and also inaccurate) since the method is well named `deleteUserById` and well typed `Promise<void>`.

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +    return this.userRepository.nativeDelete(user_id).then(() => {
Case should be consistent :
```suggestion
  async deleteUserById(userId: number): Promise<void> {
    return this.userRepository.nativeDelete(userId).then(() => {
```

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +   * Is the username already in database ?
Again I think you named it suffifciently well to remove this comment.

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +        return 0;
Not fond of this, since zero is a valid number.

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +   * @return number The user_id
These param and return are inaccurate.
Plus typescript is already giving us more accurate info, you should remove these.

2023-02-27 18:18 UTC, lutangar commented on apps/backend/src/user/user.service.ts
> +   * Sends the user id when given user name. Sends 0 if username not found or incoherent.
```suggestion
   * Returns the user id for given username. Returns 0 if the username isn't found or incoherent.
```

2023-02-27 18:18 UTC, lutangar commented on apps/shared/models/dto/user/user.dto.ts
> +  // admin || editor
Should be an enum then.

2023-02-27 18:18 UTC, lutangar commented on apps/shared/models/dto/user/userPublic.dto.ts
> +    this.userid = userId;
Case should be consistent :
```suggestion
  readonly userId: number;
  readonly username: string;
  readonly role: string;
  readonly active: boolean;

  constructor(userId: number, userName: string, userRole: string, userIsActive: boolean) {
    this.userId = userId;
```

2023-02-27 18:18 UTC, lutangar commented on apps/shared/models/dto/user/userPublic.dto.ts
> +    this.userid = userId;
Or should it be just named `id` instead ?

2023-02-28 08:40 UTC, racine-p-a commented on apps/backend/cypress.config.js
> +    baseUrl: 'http://localhost:3333',
Issue added https://github.com/datatlas-erasme/datatlas/issues/80

2023-02-28 08:44 UTC, racine-p-a commented on apps/backend/src/app/app.controller.spec.ts
> -import { Test, TestingModule } from '@nestjs/testing';
As we discussed, this will be updated with next @Pipazoul update

2023-02-28 11:10 UTC, merged